### ISSUE TITLE
Crashe on Clear()

### ISSUE THREAD

**Issue by PCDK** [daniel-luberda/DLToolkit.Forms.Controls#140]
Hey, I have a simple `FlowListView` with an `FlowItemsSource` as a `ObservableCollection`. When I call Clear() on my `ObservableCollection` in a call like `PullToRefresh` the `FlowListView` crashes the app with an exception: _InvalidOperationException: Sequence contains no elements_

I think it is because of the following call in _FlowObservableCollection.cs_ on line 139:
`var isGroup = updateItems.First() is FlowGroup;`
I have not tested it though.

Here is my stacktrace:

```
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable 1[T] source)
at DLToolkit.Forms.Controls.FlowObservableCollection 1[T].SyncPrivate (DLToolkit.Forms.Controls.FlowObservableCollection 1[T] currentItems, DLToolkit.Forms.Controls.FlowObservableCollection 1[T] updateItems, System.Boolean notify)
at DLToolkit.Forms.Controls.FlowObservableCollection 1[T].Sync (DLToolkit.Forms.Controls.FlowObservableCollection 1[T] newItems, System.Boolean notify)
at DLToolkit.Forms.Controls.FlowListView.UpdateContainerList ()
at DLToolkit.Forms.Controls.FlowListView.ForceReload (System.Boolean updateOnly)
at DLToolkit.Forms.Controls.FlowListView.FlowItemsSourceCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e
at System.Collections.ObjectModel.ObservableCollection 1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection 1[T].OnCollectionReset ()
at System.Collections.ObjectModel.ObservableCollection 1[T].ClearItems ()
at System.Collections.ObjectModel.Collection 1[T].Clear ()
```

**Comment by ArMzAdOg** [comment]
+1

**Comment by ArMzAdOg** [comment]
FlowEmptyTemplate solve this issue

**Comment by daniel-luberda** [comment]
Should be fixed now.

**Comment by alferretti** [comment]
Hello, I don't know how this nuget shitfest works, and if it this the right place to ask this, but is there a way to fetch this bugfix from your repo? I have your FlowListView 2.0.9 package installed from Nuget package manager, but I still have this issue. Or is there a way to bypass that bug until you update the package? 

Thanks for your help !

-- Alex
